version: '3'

services: 
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "python build.py && python idealista/manage.py makemigrations && python idealista/manage.py migrate && python idealista/manage.py runserver 0.0.0.0:8000"
    container_name: web
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'oportunista'
    ports:
      - '3306:3306'
